services:
  - type: web
    plan: free
    name: Auto Rename Bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 PandaXAshu.py
    repo: 
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: FORCE_SUB_CHANNELS
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_URL
        sync: false
      - key: START_PIC
        sync: false
      - key: ADMIN
        sync: false
      - key: WEBHOOK
        sync: false
